version: "3.0"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.40
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
      MYSQL_ROOT_PASSWORD: moodlepassword
    ports:
      - "3306:3306"
    volumes:
      - ./db/moodledb:/var/lib/mysql

  ava:
    container_name: moodle
    image: moodle-template
    security_opt:
      - label:disable
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./db/install.sh:/db/install.sh:ro
      - ./db/moodledata:/var/moodle_shared/moodledata
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    environment:
      DB_HOST: mysql
      DB_NAME: moodle
      DB_USER: moodleuser
      DB_PASS: moodlepassword
    command: >
      sh -c "
        echo '(01) Executando install.sh:'
        cat /db/install.sh | dos2unix > /db/normalized.sh
        chmod +x /db/normalized.sh
        /db/normalized.sh
        echo '(03) Configurando openrc:'
        mkdir /run/openrc/ && touch /run/openrc/softlevel
        echo '(04) Iniciando o Apache no Ubuntu:'
        service apache2 start
        echo '(05) Dando permissão ao moodledata:'
        chmod 777 /var/moodle_shared/moodledata
        echo '(06) Exibindo os logs:'
        cron -l 8 -b > /dev/stdout 2> /dev/stderr &
        tail -f /var/log/apache2/error.log
      "

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - ava
